# Nginx 최신 Alpine 이미지 사용 (경량화)
FROM nginx:alpine

# Nginx 리버스 프록시 설정 복사
COPY ./default.conf /etc/nginx/conf.d/default.conf

# 커스텀 페이지 복사
COPY ./index.html /usr/share/nginx/html/index.html

# 80 포트 노출
EXPOSE 80

# Nginx 실행 (포그라운드 모드)
CMD ["nginx", "-g", "daemon off;"]
