# Nginx All-in-One YAML for Namespace: 3tier-nginx

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: 3tier-nginx

---
# Secret - GitLab Container Registry 인증
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: 3tier-nginx
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON_BASE64}

---
# ConfigMap - Nginx 설정
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: 3tier-nginx
data:
  default.conf: |
    charset utf-8;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # FQDN 사용
        # FastAPI Root API 프록시
        location /api/ {
            proxy_pass http://fastapi-service.3tier-fastapi.svc.cluster.local:8000/;
        }

        # FQDN 사용
        # FastAPI Member API 프록시
        location /member {
            proxy_pass http://fastapi-service.3tier-fastapi.svc.cluster.local:8000/member;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>3-TIER 구성하기</title>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
            function callRoot() {
                $.ajax({
                    url: "/api/",
                    method: "GET",
                    dataType: "json",
                    success: function (data) {
                        document.getElementById('result').innerText = JSON.stringify(data, null, 2);
                    },
                    error: function (xhr, status, error) {
                        document.getElementById('result').innerText = "Error: " + error;
                    }
                });
            }

            function callMember() {
                $.ajax({
                    url: "/member",
                    method: "GET",
                    dataType: "json",
                    success: function (response) {
                        if (response.message === "success" && response.data) {
                            var str = "ID | User ID | Name | Email | Phone\n";
                            str += "-----------------------------------\n";
                            for (var i = 0; i < response.data.length; i++) {
                                var row = response.data[i];
                                str += row.id + " | " + row.user_id + " | " + row.name + " | " + row.email + " | " + row.phone + "\n";
                            }
                            document.getElementById('result').innerText = str;
                        } else {
                            document.getElementById('result').innerText = JSON.stringify(response, null, 2);
                        }
                    },
                    error: function (xhr, status, error) {
                        document.getElementById('result').innerText = "Error: " + error;
                    }
                });
            }
        </script>
    </head>
    <body>
        <h1>FastAPI + MySQL 3-Tier</h1>
        <div>
            <button onclick="callRoot()">/ (Root API)</button>
            <button onclick="callMember()">/member (MySQL 연결)</button>
        </div>
        <h2>결과:</h2>
        <pre id="result">버튼을 클릭하세요</pre>
    </body>
    </html>

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: 3tier-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: nginx-container
        image: registry.gitlab.com/pyh5523/pista-megazoncloud/3tier-nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
      - name: nginx-html
        configMap:
          name: nginx-config
          items:
          - key: index.html
            path: index.html
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: 3tier-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
