# FastAPI All-in-One YAML for Namespace: 3tier-fastapi

# 배포 방법:
#   1. .env 파일 생성
#   2. .env 파일 수정
#   3. set -a && source .env && set +a && envsubst < fastapi/fastapi.yaml | kubectl apply -f -

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: 3tier-fastapi

---
# Secret - MySQL 인증정보 (3tier-mysql에서 복사)
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: 3tier-fastapi
type: Opaque
stringData:
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  MYSQL_DATABASE: "${MYSQL_DATABASE}"

---
# Secret - GitLab Container Registry 인증
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: 3tier-fastapi
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON_BASE64}

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: 3tier-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-pod
  template:
    metadata:
      labels:
        app: fastapi-pod
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: fastapi-container
        image: registry.gitlab.com/pyh5523/pista-megazoncloud/3tier-fastapi:latest
        ports:
        - containerPort: 8000
        env:
        #  FQDN 사용
        - name: MYSQL_HOST
          value: "mysql-service.3tier-mysql.svc.cluster.local"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: 3tier-fastapi
spec:
  type: ClusterIP
  selector:
    app: fastapi-pod
  ports:
  - port: 8000
    targetPort: 8000
